[gcp_service_account]
type = "service_account"
project_id = "inductive-world-481016-i6"
private_key_id = "fd675d495182dcc9a161c5aff1854c83c69feb8f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGzDetMHZfYAZN
QJxSbR1tCayKbw/RTwuU3Fol9n5gz4Ao3xzt4EbPI5qJYnG07Y43a6jtUpsnzpVd
7VVsqKuLQ4WKIEaQPEBN81ConNzqGJiv/b6K7Wx9jQnH9/+KoSN+I2c6S9O47r/B
UxtgXoNzgCXql4C/Cf8bz1PZajEzZ+CddCJtuwAfTynvZal/x95dcQG1YtbteLIh
St/ZI70t+cZsv5+SwkZYQ8YtF4fXyB1nqtWkac1F2eI6DmpjMLVgkOHK084PNY+k
DpZ8Ynt8tEDOiwmCq77UOsrQ6Eya7ay0tq1OhSOxv7nSGbAh4u0zn0HdhNxkH6Ni
YxLhTsLRAgMBAAECggEACfbwj4DPXiZ9CmBDtan8gJush1/bxh0VMof9CMwbN5UP
En1kgNPuGLHrLBnAI1aI+2QtGoA6gLtNJ2EfGAw4VQm0ZuEJSG+MtZuNnnYGaMGE
3cV1SJdwCbcJF3np2DQNiGQT54sneKyW9gTJaYIzSpXQ0Lp5XJoOrIEu7cXx42ap
5KhbNMxt3zDNCe4wAlcMdJbLAwoREtFJZxgQsCZKFwvzkrk97tiv8rxkmY4H/vp0
0Ha7x1jP9LsVIhBYxaFYAuzUrfBhQbIfVGdCwGW27G+i+osD8q4X+jEs3+KploxZ
Qr/5gcEOMcJmj1E+U+e/8KB0uZ9YaiGUGGakrMAcMQKBgQDwywbPbZEEJ8MuTT/2
Z1JnbX+SemEAJ+nzZV6nZ49SKCizbml0/ohKz1xNbG/QYOEREHuoSlK91w0SFstp
kJXdawf/qATgWBEHpMiYOnJEe0QdAida2JMPtGE4rIJz8X7U35SPfYKjGeBtjEZV
1e2MRoZRKEJL0gCcKYcvbjpYRQKBgQDTWj1UeCBsrvEKTh8AmEJvt9BsXDMBBM8F
JzIkAmAbveJTi3txkPunkjqsvGXSqUm5Rf87N5lV6sidjL3Vat77eWePZGu1Xbo7
lbXPhrbVWPzZXHt9l5+vfeZErM+3XowU7Aa+N618FnZNJucYvvok9/oNdUYliSjo
XQnwbuNnHQKBgBBT9BZEu7yoZZfSLTAsOW5CApCQM9uq2TZj/VMktpc/meLw7b29
NMi93uhxHfPnXdumXnw+7fVpi71aRljWMRNemqA/aHU+A4mdJu0LqYvzP98nsjt6
zB4YgS8yo3XxPkR5FL3WKPGeY5WKGYrggscsURdXv4ccqmXsevpAYzxxAoGBAJ6z
xRe3eEmD95VQYfE1Y7W15fhoJxhdvwHUk878RaSvKdKoCxKU1pLWt95bPW45FhXc
HLIfprEgMnIza5xkunlEiWHf+wzeC2iQm0vwkTuUrZCd5FDDWPIS7KSmyvabNT7E
mK+e6VMjHsQCMUegp/64gfg3Fmw7GQ+aRUtYSMN1AoGBALXnL8mwlZNK5zjBQScO
PTPE2nEJiuX7Mi9ZURnoj6w/OX3cmsBgedk+rD11fOneX/rj5qn3A2ucTe1umDh0
XEURwb214VuXrefNUcl27EmOhytxuAfUNM5gV6qvDRy7XM0vbY8gMK6iTkgLmkBW
2w6N7gLADIQFoX6RkiTrM2SB
-----END PRIVATE KEY-----"""
client_email = "streamlit-drive-access@inductive-world-481016-i6.iam.gserviceaccount.com"
client_id = "108720459182873249091"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-drive-access%40inductive-world-481016-i6.iam.gserviceaccount.com"

[drive_folders]
contract_view = "1aFTqvh0zDgQn6Wuw08xjuuNZX1cTh1ZU"
supply_view   = "1BNgpUZoD6JQKFFFKur1n8JYtxt1_uE-3"